name: Code Check
description: Run code style checks and tests

inputs:
  cache-prefix:
    description: Prefix for cache keys
    type: string
    default: ""
    required: false
  github-token:
    description: GitHub token for authentication
    required: true

runs:
  using: composite
  steps:
    - name: Setup Environment
      uses: ./.github/actions/setup
      with:
        cache-key: ${{ inputs.cache-prefix }}style-check
        github-token: ${{ inputs.github-token }}

    - name: Check formatting & lint
      shell: bash
      run: |
        nix develop --command just fmt --check
        nix develop --command just lint
        nix develop --command just audit

    - name: Run tests
      shell: bash
      run: nix develop --command just test
