name: Code Check

on:
  workflow_call:
    inputs:
      cache-prefix:
        description: Prefix for cache keys
        type: string
        default: ""
        required: false

permissions:
  contents: read

jobs:
  style:
    name: Check Style & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cache-key: ${{ inputs.cache-prefix }}style-check
          github-token: ${{ github.token }}

      - name: Check formatting & lint
        run: |
          nix develop --command just fmt --check
          nix develop --command just lint
          nix develop --command just audit

  tests:
    name: Run Tests
    needs: [style, audit]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cache-key: ${{ inputs.cache-prefix }}test-${{ matrix.os }}
          github-token: ${{ github.token }}

      - name: Run tests
        run: nix develop --command just test
