# 复用的工作流配置
name: Workflow Configs

# 这个文件只是配置，不会被直接运行
on:
  workflow_call:
    inputs:
      release_type:
        required: true
        type: string
        description: "Release type: stable or nightly"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1
  APP_NAME: gpui-demo
  RUST_LOG: info
  MACOSX_DEPLOYMENT_TARGET: "10.15"
  CARGO_BUILD_TARGET: "x86_64-apple-darwin"
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 2

jobs:
  style:
    name: Check Style & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "style-check"
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Check formatting & lint
        run: |
          nix develop --command just fmt --check
          nix develop --command just lint

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run security audit
        run: nix develop --command just audit

  tests:
    name: Run Tests
    needs: [style, audit]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "test-${{ matrix.os }}"
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Run tests
        run: nix develop --command just test
