name: PR Check

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".vscode/**"
      - ".idea/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".vscode/**"
      - ".idea/**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1
  RUST_BACKTRACE: 1
  RUST_LOG: error
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 2

jobs:
  check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Checks
        uses: ./.github/actions/check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
