name: PR Check

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".vscode/**"
      - ".idea/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1
  RUST_BACKTRACE: 1
  RUST_LOG: error
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 2

jobs:
  check:
    name: Code Check
    uses: ./.github/workflows/check.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
