name: PR Check

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".vscode/**"
      - ".idea/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".vscode/**"
      - ".idea/**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1
  RUST_BACKTRACE: 1
  RUST_LOG: error
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 2

jobs:
  check:
    name: Code Check
    if: ${{ !contains(github.event.head_commit.message, 'Version Packages') }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Checks
        uses: ./.github/actions/check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
