name: Release

on:
  push:
    branches:
      - main

permissions: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  versions:
    name: Create Release PR or Publish
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    outputs:
      has_changesets: ${{ steps.changesets.outputs.hasChangesets }}
      need_publish: ${{ steps.need_publish.outputs.need_publish }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Setup Node package manager
        uses: pnpm/action-setup@v3

      - name: Install Node dependencies
        run: pnpm install

      - name: Verify Versions
        run: nix develop --command just verify-versions

      - name: Changesets check
        id: changesets
        uses: changesets/action@v1
        with:
          version: nix develop --command just versions-sync
          publish: echo "need_publish=true" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs: versions
    # when need_publish is true, release
    if: ${{ needs.versions.outputs.need_publish == 'true' }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: bundle-mac
            artifact: macos-bundle
            paths: |
              target/release/*.app
              target/release/*.dmg
          # - os: ubuntu-latest
          #   target: bundle-linux
          #   artifact: linux-bundle
          #   arch: x86_64
          #   paths: ${{ vars.APP_NAME }}-linux-x86_64.tar.gz
          # - os: ubuntu-latest
          #   target: bundle-linux
          #   artifact: linux-bundle
          #   arch: aarch64
          #   paths: ${{ vars.APP_NAME }}-linux-aarch64.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-${{ matrix.os }}-${{ matrix.arch }}"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Rust Release
        run: |
          nix develop --command just release

      - name: Bundle
        run: |
          if [ "${{ matrix.target }}" = "bundle-linux" ]; then
            nix develop --command just ${{ matrix.target }} ${{ matrix.arch }}-unknown-linux-gnu
            nix develop --command just linux-verify
          else
            nix develop --command just ${{ matrix.target }}
            nix develop --command just mac-verify
            nix develop --command just mac-create-dmg
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.paths }}

  publish:
    name: Publish
    needs: [versions, release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Download All Artifacts
        uses: actions/download-artifact@v4

      - name: Generate Checksums
        id: checksums
        run: |
          ls -la
          find . -type f \( -name "*.dmg" -o -name "*.tar.gz" -o -name "*.app" \) -exec sha256sum {} \; > checksums.txt
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat checksums.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: |
            macos-bundle/*
            linux-bundle/*
            checksums.txt
          generate_release_notes: true
          body: |
            ## Release Notes
            Please see CHANGELOG.md for details.

            ## SHA-256 Checksums
            ```
            ${{ steps.checksums.outputs.content }}
            ```
